spring:
  application:
    name: ms-credit
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://devuser:devpassword@localhost:27017/credit_db?authSource=admin
  kafka:
    consumer:
      group-id: ms-credit
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: java.util.Map

server:
  port: 8083

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
